---
- hosts: all
  become: True
  ignore_errors: True
  gather_facts: yes
  #become_user: root

  tasks:
      - name: Create a file
        file:
          path: /tmp/playbookfile
          mode: '0755'
          state: touch
        tags:
            - file

      - name: check something
        command: jdjdkkdjdj
        

      - name: Create a directory
        file:
          path: /tmp/dir
          mode: '0700'
          state: directory
        tags:
            - dir

      - name: Create group
        group:
          state: present
          name: Security

      - name: Create user
        user:
          comment: Steve Admin
          shell: /bin/bash
          group: Security
          name: Steve
        when: ansible_os_family =="Debian" or ansible_processor_nproc > 2

      - name: Check uptime
        command: uptime
      - name: Check Date
        shell: cat /etc/passwd | grep Steve